# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  clean: true
  path: nodejs-express-kubernetes
  fetchDepth: 1

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'ls -r'
    workingDirectory: '$(Agent.BuildDirectory)'

- task: AzureWebAppContainer@1
  displayName: 'Deploy Node App'
  inputs:
    azureSubscription: 'nicmaysAIRS'
    appName: 'nodesamplebackend'
    multicontainerConfigFile: "$(Agent.BuildDirectory)/src/docker-compose-node-api-app-service.yml"